### ISSUE TITLE
謝謝你的心得與筆記

### ISSUE THREAD

**Issue by azole** [youjenwen/nodejs-workshop#1]
我可以問一下為什麼上課前會很擔心嗎？？？？

> 畢竟已經是成人，多數想法已經被禁錮

我反而覺得，正因為已經是成人了，成人了，就要為自己負責，不管過去如何、不管過去的家庭與教育如何，作為一個成年人，自己要去思考：你現在、你將來想要變成怎麼樣的人？ 

有了想法之後，就要幫自己找到方法，朝那個目標去邁進，也許過程中會因為接觸到到更多事物，而對原本的目標有所調整，這些都是可以的，但自己要為自己負責，例如，自己應該要為自己找到適合自己學習的方式，這也是一種為自己負責的行為。所以，你的結論很棒：

> 首先還是要重新鼓起勇氣去改變自身想法，多多鼓勵自己，不要跟別人比較，相信一切會變好。

多給自己一點時間跟機會，持續累積，你一定會變好的。

**Comment by youjenwen** [comment]
謝謝老師，覺得這一天有被療癒到。
上課前為什麼會擔心，因為很未知啊～
雖然還是來上課，就是既期待又怕受傷害的狀況吧，當然也怕課程跟不上之類的原因。
我相信自己會變好，只是有時候會不知道該怎麼度過變好的過程，所以常常會有很多想法，每次都在推翻上一次的想法，一直反覆然後原本的擔心害怕會慢慢消失，好像這是一個必經之路。

**Comment by azole** [comment]
對，那是一個必經的過程，而且每一個人都一樣，所以你可能沒有特別好，但你也絕對沒有特別糟，這世界上 80% 的人都差不多，但最後，能幫自己找到方法的撐下去的，就脫穎而出了。

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/2560515/181481009-13a9dd17-7f25-47c2-9e56-82ae346b32ec.png">
